// <auto-generated />
using JWTDemo.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace JWTDemo.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250413173948_ProductsSampleData2")]
    partial class ProductsSampleData2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("JWTDemo.Model.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductId"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StockQuantity")
                        .HasColumnType("int");

                    b.HasKey("ProductId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ProductId = 1,
                            Description = "Ergonomic wireless mouse with USB nano receiver",
                            Price = 19.99m,
                            ProductName = "Wireless Mouse",
                            StockQuantity = 120
                        },
                        new
                        {
                            ProductId = 2,
                            Description = "Backlit mechanical keyboard with red switches",
                            Price = 59.99m,
                            ProductName = "Mechanical Keyboard",
                            StockQuantity = 75
                        },
                        new
                        {
                            ProductId = 3,
                            Description = "Full HD monitor with adjustable stand",
                            Price = 189.99m,
                            ProductName = "27-inch Monitor",
                            StockQuantity = 40
                        },
                        new
                        {
                            ProductId = 4,
                            Description = "Fast charging USB-C wall adapter",
                            Price = 24.99m,
                            ProductName = "USB-C Charger",
                            StockQuantity = 200
                        },
                        new
                        {
                            ProductId = 5,
                            Description = "Portable USB 3.0 hard drive",
                            Price = 69.99m,
                            ProductName = "External Hard Drive 1TB",
                            StockQuantity = 60
                        },
                        new
                        {
                            ProductId = 6,
                            Description = "Cooling pad with dual fans and adjustable height",
                            Price = 29.99m,
                            ProductName = "Laptop Cooling Pad",
                            StockQuantity = 95
                        },
                        new
                        {
                            ProductId = 7,
                            Description = "Wireless over-ear headphones with mic",
                            Price = 49.99m,
                            ProductName = "Bluetooth Headphones",
                            StockQuantity = 80
                        },
                        new
                        {
                            ProductId = 8,
                            Description = "1080p USB webcam with auto light correction",
                            Price = 39.99m,
                            ProductName = "HD Webcam",
                            StockQuantity = 50
                        },
                        new
                        {
                            ProductId = 9,
                            Description = "Adjustable desk stand for smartphones",
                            Price = 14.99m,
                            ProductName = "Smartphone Holder",
                            StockQuantity = 130
                        },
                        new
                        {
                            ProductId = 10,
                            Description = "Digital drawing tablet with pressure sensitivity",
                            Price = 89.99m,
                            ProductName = "Graphic Tablet",
                            StockQuantity = 25
                        },
                        new
                        {
                            ProductId = 11,
                            Description = "LED ring light for streaming and photography",
                            Price = 21.99m,
                            ProductName = "LED Ring Light",
                            StockQuantity = 70
                        },
                        new
                        {
                            ProductId = 12,
                            Description = "Compact wireless keyboard with silent keys",
                            Price = 27.99m,
                            ProductName = "Wireless Keyboard",
                            StockQuantity = 100
                        },
                        new
                        {
                            ProductId = 13,
                            Description = "High-speed USB 3.0 flash drive",
                            Price = 11.49m,
                            ProductName = "USB Flash Drive 64GB",
                            StockQuantity = 150
                        },
                        new
                        {
                            ProductId = 14,
                            Description = "In-ear earbuds with noise isolation",
                            Price = 34.99m,
                            ProductName = "Noise Cancelling Earbuds",
                            StockQuantity = 90
                        },
                        new
                        {
                            ProductId = 15,
                            Description = "Wired gaming mouse with DPI settings",
                            Price = 32.99m,
                            ProductName = "Gaming Mouse",
                            StockQuantity = 85
                        },
                        new
                        {
                            ProductId = 16,
                            Description = "Portable mini projector for home theater",
                            Price = 129.99m,
                            ProductName = "Mini Projector",
                            StockQuantity = 30
                        },
                        new
                        {
                            ProductId = 17,
                            Description = "Gold-plated HDMI cable, 4K compatible",
                            Price = 8.99m,
                            ProductName = "HDMI Cable 6ft",
                            StockQuantity = 180
                        },
                        new
                        {
                            ProductId = 18,
                            Description = "Water-resistant laptop sleeve with zipper",
                            Price = 18.99m,
                            ProductName = "Laptop Sleeve 15.6\"",
                            StockQuantity = 140
                        },
                        new
                        {
                            ProductId = 19,
                            Description = "Wi-Fi smart plug with Alexa and Google support",
                            Price = 22.49m,
                            ProductName = "Smart Plug",
                            StockQuantity = 110
                        },
                        new
                        {
                            ProductId = 20,
                            Description = "Waterproof speaker with deep bass",
                            Price = 35.99m,
                            ProductName = "Portable Bluetooth Speaker",
                            StockQuantity = 60
                        });
                });

            modelBuilder.Entity("JWTDemo.Model.UserDemo", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId");

                    b.ToTable("TblUsers");

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            Password = "admin",
                            Role = "admin",
                            Username = "admin"
                        },
                        new
                        {
                            UserId = 2,
                            Password = "1",
                            Role = "user",
                            Username = "User1"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
